site_name: EPS_2020_G5 
theme:
    name: material
nav:
    - Home: index.md
    - ReuniÃµes:
        - "07/02/2021": "ReuniÃ£o dia 07-02-2021.md"
        - "01/03/2021": "dailies/01-03-2021.md"
        - "02/03/2021": "dailies/02-03-2021.md"
        - "03/03/2021": "dailies/03-03-2021.md"
        - "04/03/2021": "dailies/04-03-2021.md"
